/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_CxWave_Wave_Framework_Utils_AAA_PamUtils */

#ifndef _Included_com_CxWave_Wave_Framework_Utils_AAA_PamUtils
#define _Included_com_CxWave_Wave_Framework_Utils_AAA_PamUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_CxWave_Wave_Framework_Utils_AAA_PamUtils
 * Method:    authenticateUsingWaveCpp
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_CxWave_Wave_Framework_Utils_AAA_PamUtils_authenticateUsingWaveCpp
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
