/*************************************************************************************************************************
 * Copyright (C) 2015-2016 Vidyasagara Guntaka & CxWave, Inc * All rights reserved. * Author : Vidyasagara Reddy Guntaka *
 *************************************************************************************************************************/

package com.CxWave.Wave.Framework.Core.Test;

import com.CxWave.Wave.Framework.Type.UI32;
import com.CxWave.Wave.Framework.Type.WaveOperationCodeInterface;

public enum FrameworkTestabilityOpCodes implements WaveOperationCodeInterface
{
    FRAMEWORK_TESTABILITY_MESSAGE1,
    FRAMEWORK_TESTABILITY_MESSAGE2,
    FRAMEWORK_TESTABILITY_MESSAGE3,
    FRAMEWORK_TESTABILITY_MESSAGE4,
    FRAMEWORK_TESTABILITY_MESSAGE5,
    FRAMEWORK_TESTABILITY_MESSAGE6,
    FRAMEWORK_TESTABILITY_MESSAGE7,
    FRAMEWORK_TESTABILITY_MESSAGE8,
    FRAMEWORK_TESTABILITY_MESSAGE9,
    FRAMEWORK_TESTABILITY_MESSAGE10,
    FRAMEWORK_TESTABILITY_MESSAGE11,
    FRAMEWORK_TESTABILITY_EVENT1,
    FRAMEWORK_TESTABILITY_EVENT2,
    FRAMEWORK_TESTABILITY_EVENT3,
    FRAMEWORK_TESTABILITY_EVENT4,
    FRAMEWORK_TESTABILITY_EVENT5,
    FRAMEWORK_TESTABILITY_EVENT6,
    FRAMEWORK_TESTABILITY_EVENT7,
    FRAMEWORK_TESTABILITY_EVENT8,
    FRAMEWORK_TESTABILITY_EVENT9,
    FRAMEWORK_TESTABILITY_MANAGEMENT_INTERFACE_MESSAGE1,
    FRAMEWORK_TESTABILITY_MANAGEMENT_INTERFACE_MESSAGE2,
    FRAMEWORK_TESTABILITY_MANAGEMENT_INTERFACE_MESSAGE3,
    FRAMEWORK_TESTABILITY_MANAGEMENT_INTERFACE_MESSAGE4,
    FRAMEWORK_TESTABILITY_MANAGEMENT_INTERFACE_MESSAGE_FOR_MEMORY_LEAKS,
    FRAMEWORK_TESTABILITY_MANAGEMENT_INTERFACE_MESSAGE_FOR_OBJECT_LEAKS,
    FRAMEWORK_TESTABILITY_MANAGEMENT_INTERFACE_FILE_SERVICE_USAGE,
    FRAMEWORK_TESTABILITY_MANAGEMENT_INTERFACE_TRACK_LEAKS_WITH_BT,

    FRAMEWORK_TESTABILITY_4_GET_MANAGED_OBJECTS,
    FRAMEWORK_TESTABILITY_6_GET_MANAGED_OBJECTS;

    @Override
    public UI32 getOperationCode ()
    {
        return (new UI32 (ordinal ()));
    }

    @Override
    public int getOperationCodeIntValue ()
    {
        return (ordinal ());
    }
}
