/***************************************************************************
 *   Copyright (C) 2005-2008 Vidyasagara Guntaka                           *
 *   All rights reserved.                                                  *
 *   Author : Vidyasagara Reddy Guntaka                                    *
 ***************************************************************************/

#include "Framework/Utils/WaveSourceGenerator/WaveSourceGeneratorForMessage.h"

namespace WaveNs
{

WaveSourceGeneratorForMessage::WaveSourceGeneratorForMessage (const string &name, const string &nameSpace)
    : WaveSourceGeneratorBase (name, nameSpace)
{
}

WaveSourceGeneratorForMessage::~WaveSourceGeneratorForMessage ()
{
}

string WaveSourceGeneratorForMessage::generateClassName () const
{
    return (m_name + "Message");
}

string WaveSourceGeneratorForMessage::generateHIncludes () const
{
    string hIncludes = "#include \"Framework/Messaging/Local/WaveMessage.h\"\n"
                       "\n";

    return (hIncludes);
}

string WaveSourceGeneratorForMessage::generateHClassBegin () const
{
    string classBegin = "class " + generateClassName () + " : public WaveMessage\n"
                        "{\n";

    return (classBegin);
}

string WaveSourceGeneratorForMessage::generateHClassMemberFunctionsPrivate () const
{
    string memberFunctionsPrivate = "    private :\n"
                                    "        void setupAttributesForSerialization ();\n"
                                    "\n";

    return (memberFunctionsPrivate);
}

string WaveSourceGeneratorForMessage::generateHClassMemberFunctionsPublic () const
{
    string memberFunctionsPublic = "    public :\n"
                                   "                 " + generateClassName () + " ();\n"
                                   "        virtual ~" + generateClassName () + " ();\n";

    return (memberFunctionsPublic);
}

string WaveSourceGeneratorForMessage::generateCppMemberFunctions () const
{
    string memberFunctions;

    memberFunctions += generateClassName () + "::" + generateClassName () + " ()\n"
                       "    : WaveMessage (<OMID>, <OPCODE>)\n"
                       "{\n"
                       "}\n"
                       "\n";

    memberFunctions += generateClassName () + "::~" + generateClassName () + " ()\n"
                       "{\n"
                       "}\n"
                       "\n";

    memberFunctions += "void " + generateClassName () + "::setupAttributesForSerialization ()\n"
                       "{\n"
                       "    WaveMessage::setupAttributesForSerialization ();\n"
                       "\n"
                       "    // This class Specific Attributes below\n"
                       "    <AUTOGENERATED : FILLME>\n"
                       "}\n"
                       "\n";

    return (memberFunctions);
}

}
