/*************************************************************************************************************************
 * Copyright (C) 2015-2015 Vidyasagara Guntaka & CxWave, Inc * All rights reserved. * Author : Vidyasagara Reddy Guntaka *
 *************************************************************************************************************************/

package com.CxWave.Wave.Framework.ObjectModel;

public enum WaveWorkerPriority
{
    WAVE_WORKER_PRIORITY_0, WAVE_WORKER_PRIORITY_1, WAVE_WORKER_PRIORITY_2, WAVE_WORKER_PRIORITY_3, WAVE_WORKER_PRIORITY_4, WAVE_WORKER_PRIORITY_5, WAVE_WORKER_PRIORITY_6, WAVE_WORKER_PRIORITY_7, WAVE_WORKER_PRIORITY_8, WAVE_WORKER_PRIORITY_9, WAVE_WORKER_PRIORITY_10, WAVE_WORKER_PRIORITY_11, WAVE_WORKER_PRIORITY_12, WAVE_WORKER_PRIORITY_13, WAVE_WORKER_PRIORITY_14, WAVE_WORKER_PRIORITY_15, WAVE_WORKER_PRIORITY_16, WAVE_WORKER_PRIORITY_17, WAVE_WORKER_PRIORITY_18, WAVE_WORKER_PRIORITY_19, WAVE_WORKER_PRIORITY_20, WAVE_WORKER_PRIORITY_21, WAVE_WORKER_PRIORITY_22, WAVE_WORKER_PRIORITY_23, WAVE_WORKER_PRIORITY_24, WAVE_WORKER_PRIORITY_25, WAVE_WORKER_PRIORITY_26, WAVE_WORKER_PRIORITY_27, WAVE_WORKER_PRIORITY_28, WAVE_WORKER_PRIORITY_29, WAVE_WORKER_PRIORITY_30, WAVE_WORKER_PRIORITY_31
}
